### ISSUE TITLE
小白求助~我完全按照说明运行了，也产生了日志，但是没有显示连接成功日志，发消息也没反应

### ISSUE THREAD

**Issue by Veniamare** [MangataTS/kaptreebot#1]
02-12 21:08:20 [INFO] nonebot | NoneBot is initializing...
02-12 21:08:20 [INFO] nonebot | Current Env: prod
02-12 21:08:20 [INFO] nonebot | Succeeded to import "nonebot.plugins.echo"
02-12 21:08:20 [INFO] nonebot | Succeeded to import "TransPlugin"
02-12 21:08:20 [INFO] nonebot | Succeeded to import "WeatherPlugin"
02-12 21:08:20 [INFO] nonebot | Succeeded to import "daily"
02-12 21:08:20 [INFO] nonebot | Succeeded to import "pokeme"
02-12 21:08:21 [INFO] nonebot | Succeeded to import "zhiling"
02-12 21:08:21 [INFO] nonebot | Running NoneBot...
02-12 21:08:21 [INFO] uvicorn | Started server process [14776]
02-12 21:08:21 [INFO] uvicorn | Waiting for application startup.
02-12 21:08:21 [INFO] uvicorn | Application startup complete.
02-12 21:08:21 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8765 (Press CTRL+C to quit)
到这里就没了。谢谢！

**Comment by kaptree** [comment]
你加一下我的qq 1196991321------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Yiku&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月12日(星期五) 晚上9:10
收件人:&nbsp;&quot;MangataTS/kaptreebot&quot;<kaptreebot@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[MangataTS/kaptreebot] 小白求助~我完全按照说明运行了，也产生了日志，但是没有显示连接成功日志，发消息也没反应 (#1)

**Comment by Veniamare** [comment]
已解决，感谢博主
